feat: dockerize api
Taehee-K/MLOpsCurriculum pull request #6
Opened 2022-03-28 23:55 UTC by Taehee-K

## Type of PR : [New Features, Fix, Structure changes, etc.]

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Other... Please describe:
```

## Check List
* dockerize api
## Role of Reviewer

## Description

## TODO

2022-03-29 01:20 UTC, adldotori commented
다음 에러 발생하는데 아래 링크들 참고해보시면 좋을 것 같습니다.
migrate 를 따로 안해줘서 발생하는 문제입니다.
1. https://github.com/corca-ai/emart-dashboard-back/blob/master/build/docker-compose.yml#L10
2. https://stackoverflow.com/questions/33992867/how-do-you-perform-django-database-migrations-when-using-docker-compose
3. 1,2 다 포함되어있습니다. http://daplus.net/django-docker-compose%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%A0-%EB%95%8C-django-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98%EC%9D%84/

여러가지 방법이 있으니 편한대로 해보면 됩니다.
![image](https://user-images.githubusercontent.com/19206046/160513326-12402c88-abd6-41f5-afd3-3ef84655d493.png)

2022-03-29 01:21 UTC, adldotori requested changes

2022-03-29 01:21 UTC, adldotori commented on src/api/settings.py
>  DEBUG = True
크리티컬한 건 아니긴 한데 배포하실 땐 항상항상 False로 하셔야 합니다. 지금은 커리큘럼이니까 큰 상관없지만 나중엔 꼭 신경써주세요.

2022-03-29 01:22 UTC, adldotori commented on src/api/settings.py
>  DEBUG = True
이건 따로 수정 안하셔도 됩니다 :)

2022-03-29 01:25 UTC, Taehee-K commented
> migrate 를 따로 안해줘서 발생하는 문제입니다.

`docker compose run backend python manage.py migrate` 식으로 실행을 시켰었는데 `docker-compose.yml`에 포함되도록 수정하겠습니다!

2022-03-29 07:51 UTC, hanchchch approved these changes

2022-03-29 07:51 UTC, hanchchch commented on src/api/settings.py
> -ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
ALLOWED_HOSTS 는 CORS 이슈랑 관련된 보안 설정으로, 한 줄로 설명드리자면 "어떤 호스트로 들어온 요청만 처리할거냐" 를 정해준다고 생각하시면 됩니다. 예를 들어 제가 docs.corca.ai 라는 도메인으로 배포했다면, 클라이언트는 요청을 보낼때 docs.corca.ai를 호스트로 해서 요청을 보내기 때문에 이 ALLOWED_HOSTS에 docs.corca.ai를 추가해야합니다. 그리고 개발중에는 localhost, 127.0.0.1 으로 요청을 보내기 때문에 이 또한 추가해야 편하겠죠. 즉 postgres는 추가하실 이유가 전혀 없습니다.

CORS 에 관한 설명은 developer.mozilla.org 에 되게 잘 되어 있습니다. 궁금하시면 한 번 읽어보세용
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
이러한 정책적인 요소가 HTTP 헤더를 통해 구현되는데 이 사이트에 헤더 관련된 설명도 매우 잘되어 있습니다. Access-Control-Allow-Origin 헤더가 이와 관련된 헤더이니 더 궁금하시면 찾아보세요~ 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

2022-03-29 07:51 UTC, hanchchch commented on requirements.txt
> +python-dotenv==0.19.2
`pip freeze > requirements.txt` 명령어로 현재 설치된 패키지를 모두 dump할 수 있습니다.
물론 이걸 활용하려면 이 프로젝트에 쓰이는 패키지만 설치되어 있어야 하므로 venv를 사용하는게 필수적입니다.
venv는 위 이유 이외에도 패키지 버전 충돌 방지나 환경 분리 등 여러 이유로 제가 항상 사용을 권장 드리고 있습니다.

2022-03-29 07:51 UTC, hanchchch commented on docker-entrypoint.sh
> +python manage.py runserver 0.0.0.0:8000
`runserver` 하실 때 `--settings` 옵션을 통해 원하는 setting 파일을 골라서 넣어줄 수 있습니다.
디폴트는 물론 `./api/settings/py`입니다. [manage.py](https://github.com/Taehee-K/MLOpsCurriculum/blob/main/src/manage.py#L9)에 이 디폴트 설정이 명시되어 있습니다.

그래서 태호님이 말씀하신 '배포할 때 바꿔줘야 할 설정' 을 간편하게 하기 위해서, 예를들어 `DEBUG=False` 를 포함하는 세팅 파일을 `./api/production.py` 로 만들고, 이런 엔트리 쉘스크립트에 
```sh
python manage.py runserver --settings api.production 0.0.0.0:8000
```
이런식으로 세팅파일을 지정해주는 방법을 많이 이용합니다.

2022-03-29 08:07 UTC, Taehee-K commented on requirements.txt
> +python-dotenv==0.19.2
현재 콘다 가상환경을 만들어서 사용하고 있는데 전체 패키지를 올리는 것이 나을까요?

2022-03-29 08:59 UTC, Taehee-K commented on docker-entrypoint.sh
> +python manage.py runserver 0.0.0.0:8000
DEBUG를 환경변수로 False 지정하는 것과의 차이점이 있을까요?

2022-03-30 02:18 UTC, Taehee-K commented
@adldotori @hanchchch `settings.py`를 `development.py`, `production.py`로 나누었는데 확인 부탁드립니다!

2022-03-30 04:31 UTC, adldotori approved these changes

2022-03-30 07:40 UTC, hanchchch commented on docker-entrypoint.sh
> +python manage.py runserver 0.0.0.0:8000
DEBUG는 boolean이므로 환경변수로 충분히 쉽게 제어가 가능한데, db 옵션 같은 경우는 dict 형태이고 db 종류에 따라 키가 달라질 수도 있기 때문에 환경변수로 관리하기 까다롭습니다. 또 중요한 설정인 ALLOWED_HOSTS 의 경우에도 List[str] 이므로 환경변수로 넣어주기 애매합니다. 이런 설정들을 다이나믹하기 위해서 일반적으로 settings를 분리해서 작성하게 되고 어차피 그렇다면 DEBUG도 따로 빼주는게 더 좋겠죠.

그리고 환경변수는 코드상에 노출이 되지 않는다는 특징이 있습니다. 이는 보안 상 장점이 있지만, DEBUG 옵션처럼 확실히 명시적으로 False를 주어야 하는 경우에는 오히려 단점이 될 수 있습니다. 배포환경에서 까먹고 DEBUG 환경변수를 설정하지 않는다면 제가 의도한대로 작동하지 않을 수도 있으니까요. 이런 경우엔 오히려 코드에 명시적으로 포함시키는게 더 나을 수 있습니다.

2022-03-30 07:42 UTC, hanchchch approved these changes
좋습니다!

2022-03-30 07:42 UTC, Taehee-K commented on docker-entrypoint.sh
> +python manage.py runserver 0.0.0.0:8000
아하 그렇군요 설명 감사합니다 😀

2022-03-30 07:45 UTC, merged